#DO NOT CHANGE, internal use only. Changing this will reset your entire config!
configver: 5

plugin:
  enabled: true
  usesql: true
  usevanishnopacket: true
  useessentials: true
  usezperms: true
#Debug mode, can get a wee bit spammy.
  debug: true

stafftracker:
#how often do we update, in seconds.
  updateInterval: 60
#How do we determine a player is a Staff Member?
  staffPerm: true
  staffGroup: true
  staffOp: true
#The permission staff have that makes them Staff. 
#IMPORTANT NOTE : This is currently -A- permission. just one!
  staffPerms: staff
#The groups staff have that makes them staff. REQUIRES VAULT OR ESSENTIALS!
  staffGroups:
    -mod
    -coadmin
    -admin
    -manager
    -founder
#Should the plugin ignore Operator status in the list, regardless of staffOp?
  ignoreOP: false

extra:
#If true, any non-staff member will have socialspy removed!
  staffOnlySocialSpy: true

mysql:
  driver: com.mysql.jdbc.Driver
  user: user
  pass: resu
  ip: 127.0.0.1
  port: 3306
  db: plugin_database
  table: stafftracker
#onNoConnect options :
#retry - Does not abort if the database is unreachable. Will continue to attempt to reconnect.
#fail - aborts SQL initialization if the database is unreachable. This will disable the plugin!
  onNoConnect: retry