name: StaffTracker
main: net.mineyourmind.mrwisski.StaffTracker
version: 0.1.0b
author: MrWisski
softdepend: [Essentials, VanishNoPacket, zPermissions]
description: Bukkit plugin to help monitor staff activity
website: https://github.com/MrWisski/StaffTracker


commands:
   st:
      description: StaffTracker help
      usage: /st help
      default: op
      permission: stafftracker.use
      
permissions:
   stafftracker.viewdetails:
      description: make use of the /st show <player> command
      default: op
   stafftracker.removerecord:
      description: make use of the /st remove <player> command
      default: false
   stafftracker.use:
      description: make use of the /st command
      default: op
